In [7]:
import gym

In [14]:
env=gym.make('CartPole-v0')
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [19]:
env=gym.make('CartPole-v0')
for i_episode in range(20):
    observation=env.reset()
    for t in range(1000):
        env.render()
        print(observation)
        action=env.action_space.sample()
        observation, reward ,done ,info = env.step(action)
        
        if done:
            print('Episode #%d finished after %d timesteps' %(i_episode,t))
            break
env.close()      #the latest updates of gym has a function for close, the option of close=True in render has been removed.
#env.render(close=True)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.01304397  0.03647567 -0.00459985  0.01195137]
[ 0.01377348 -0.15858001 -0.00436082  0.30317945]
[0.01060188 0.03660382 0.00170276 0.00912441]
[ 0.01133396  0.23170131  0.00188525 -0.28302079]
[ 0.01596798  0.42679632 -0.00377516 -0.57510852]
[ 0.02450391  0.62197099 -0.01527733 -0.86897833]
[ 0.03694333  0.81729742 -0.0326569  -1.16642514]
[ 0.05328928  0.62261533 -0.0559854  -0.88415713]
[ 0.06574159  0.81845097 -0.07366855 -1.19390147]
[ 0.08211061  0.6243563  -0.09754657 -0.92518809]
[ 0.09459773  0.82065079 -0.11605034 -1.24686331]
[ 0.11101075  0.62719243 -0.1409876  -0.99266992]
[ 0.1235546   0.43420949 -0.160841   -0.74738094]
[ 0.13223879  0.63114172 -0.17578862 -1.08605019]
[ 0.14486162  0.82809112 -0.19750962 -1.42833758]
Episode #0 finished after 14 timesteps
[ 0.00236157 -0.00622549  0.04534861  0.01453409]
[ 0.00223706  0.18821776  0.0456393  -0.263503  ]
[ 0.00600141  0.

[ 0.02485924  0.4018389  -0.04385196 -0.66079269]
[ 0.03289601  0.20735371 -0.05706782 -0.38223372]
[ 0.03704309  0.01308653 -0.06471249 -0.10807616]
[ 0.03730482  0.20907326 -0.06687401 -0.42045311]
[ 0.04148628  0.40507586 -0.07528308 -0.73344615]
[ 0.0495878   0.21107033 -0.089952   -0.46537444]
[ 0.05380921  0.40734051 -0.09925949 -0.78499968]
[ 0.06195602  0.603676   -0.11495948 -1.10718772]
[ 0.07402954  0.4102373  -0.13710323 -0.85266856]
[ 0.08223428  0.60693517 -0.15415661 -1.18512885]
[ 0.09437299  0.80368328 -0.17785918 -1.52189402]
[ 0.11044665  0.61109993 -0.20829706 -1.28959144]
Episode #8 finished after 19 timesteps
[ 0.03613532  0.03086964 -0.00400012 -0.00900573]
[ 0.03675271 -0.16419472 -0.00418023  0.28241243]
[ 0.03346881 -0.35925679  0.00146802  0.57377401]
[ 0.02628368 -0.5543993   0.0129435   0.86691904]
[ 0.01519569 -0.35945585  0.03028188  0.57833365]
[ 0.00800658 -0.55498883  0.04184855  0.88040016]
[-0.0030932  -0.75065355  0.05945655  1.18594017]
[-0.0181062

[-0.04827984 -0.77444985  0.14069528  1.35087365]
[-0.06376884 -0.97103053  0.16771275  1.68405905]
[-0.08318945 -1.16765012  0.20139394  2.02392706]
Episode #15 finished after 28 timesteps
[ 0.02598603 -0.00276182 -0.04139266  0.01990474]
[ 0.0259308  -0.19726647 -0.04099457  0.29924583]
[ 0.02198547 -0.00158488 -0.03500965 -0.00607897]
[ 0.02195377  0.19402121 -0.03513123 -0.30959905]
[ 0.02583419 -0.00058304 -0.04132321 -0.02819925]
[ 0.02582253 -0.19508877 -0.0418872   0.25116471]
[ 0.02192076 -0.38958832 -0.0368639   0.5303469 ]
[ 0.01412899 -0.58417284 -0.02625697  0.81118985]
[ 0.00244553 -0.77892544 -0.01003317  1.09549938]
[-0.01313298 -0.58367279  0.01187682  0.79968545]
[-0.02480643 -0.77895563  0.02787053  1.09608076]
[-0.04038554 -0.58421158  0.04979214  0.812271  ]
[-0.05206978 -0.38980574  0.06603756  0.5356565 ]
[-0.05986589 -0.1956715   0.07675069  0.2644908 ]
[-0.06377932 -0.39180025  0.08204051  0.5803604 ]
[-0.07161533 -0.58797018  0.09364772  0.89771846]
[-0.083374

TypeError: render() got an unexpected keyword argument 'close'

In [10]:
env.action_space

Discrete(2)

In [11]:
env.observation_space

Box(4,)